import Image from 'next/image';
import Link from 'next/link';
import Head from 'next/head';
import styles from '@styles/Home.module.css';
import { useState } from 'react';

import { useFetchBreadsQuery } from '@store/reducers/dogsApiSlice';
import DogsTable from '@components/Dogs/DogsTable';

function DogsPage() {
	const [dogsQy, setDogsQy] = useState(10);
	const { data = [], error, isLoading } = useFetchBreadsQuery(dogsQy);

	return (
		<div className='App'>
			<Head>
				<title>Dogs Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.row}>
				<h1 className={styles.title}>Dogs API Demo</h1>
			</div>
			<div className={styles.row}>
				<h2 className={styles.description}>
					The information is handle with RTK Query to show the automatic
					catching
				</h2>
			</div>
			<div className={styles.row} style={{ textAlign: 'center' }}>
				<h4>
					<code className={styles.code}>pages/breakingBad/index.js</code>
				</h4>
				<Link href='/'>
					<a style={{ fontSize: '2rem' }} className='App-link'>
						Back to Index
					</a>
				</Link>
			</div>
			<div className={styles.row} style={{ textAlign: 'center' }}>
				<p className={styles.description}>Dogs to Fetch</p>
				<select
					value={dogsQy}
					onChange={(e) => setDogsQy(Number(e.target.value))}>
					<option value='5'>5</option>
					<option value='10'>10</option>
					<option value='15'>15</option>
					<option value='20'>20</option>
				</select>
			</div>
			<div className={styles.row} style={{ textAlign: 'center' }}>
				<div
					className={styles.card}
					style={{ textAlign: 'center', width: '100%' }}>
					<span className={styles.description}>
						Number of dogs fetched : {data.length}
					</span>
				</div>
			</div>
			{error && <div>Oops!! There is some error</div>}
			{!isLoading && !error && data.length > 0 && <DogsTable data={data} />}
		</div>
	);
}

export default DogsPage;
