import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import styles from '@styles/Counter.module.css';
import { useSelector, useDispatch } from 'react-redux';

import {
	fetchAllCharacters,
	fetchCharacterById,
} from '@store/reducers/breakingBadSlice';

function BreakingBadPage() {
	const dispatch = useDispatch();

	return (
		<div className='App'>
			<Head>
				<title>Breaking Bad Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.row}>
				<h1 className={styles.title}>Breaking Bad Demo</h1>
			</div>
			<div className={styles.row}>
				<h2 className={styles.description}>
					Inspect the redux dev tools on the browser to see the results
				</h2>
			</div>
			<div className={styles.row}>
				<h4>
					<code className={styles.code}>pages/breakingBad/index.js</code>
				</h4>
			</div>
			<div className={styles.row}>
				<button
					className={styles.asyncButton}
					onClick={() => dispatch(fetchAllCharacters())}>
					Fetch Breaking Bad Characters
				</button>
			</div>
			<div className={styles.row}>
				<button
					className={styles.asyncButton}
					onClick={() => dispatch(fetchCharacterById(1))}>
					Fetch One BreakingBad Character
				</button>
			</div>
			<div className={styles.row}>
				<Link href='/'>
					<a className='App-link' style={{ fontSize: '2rem' }}>
						Back to Index
					</a>
				</Link>
			</div>
		</div>
	);
}

export default BreakingBadPage;
